shipment:
  origins:
  - Netherlands
  - Mexico
  - Israel
  - Japan
  - New Zealand
  - India
  - Tanzania
  flowers:
  - Hyacinthus
  - Rosa
  - Gerbera
  - Agapanthus
  - Aegilops
  - Protea
  - Liatris
  - Mokara
  - Anemone
  - Actinidia
  boxes:
    min: 1
    max: 50
pest:
  infestation_rate:
    distribution: beta
    parameters:
    - 4
    - 60
  arrangement: clustered
  clustered:
    max_stems_per_cluster: 5000
    distribution: gamma
    parameters:
    - 4
    - 20
  random_box:
    probability: 0.2
    ratio: 0.5
release_programs:
  naive_cfrp:
    flowers:
    - Hyacinthus
    - Gerbera
    - Rosa
    - Actinidia
    max_boxes: 10  # do not apply to shipments larger than

inspection:
  strategy: percentage
    percentage:
      proportion: 0.02
      min_boxes: 1
      unit: # TODO: how do you deal with user defined parameters in config file?
        - stems
        - boxes
    hypergeometric:
      detection_level: 0.05 # TODO: default detect at 5% infestation, how to add default and allow user input?
    first_n: # TODO: wrong syntax, these are the possible other strategies, no config info is needed for these.
    first:
    one_random:
    all:
  selection_strategy:
    - random
    - tailgate
  end_strategy: to_completion # TODO: how to add to_detection?
  within_box_pct: 100 # TODO: default to inspect all stems in box, how to add default and allow user input?
ports:
  - NY JFK CBP
  - FL Miami Air CBP
  - HI Honolulu CBP
  - AZ Phoenix CBP
  - VA Dulles CBP
  - CA San Francisco CBP
  - WA Seattle Air CBP
  - TX Brownsville CBP
  - WA Blaine CBP
# input_F280: F280_sample.csv
stems_per_box:
  default: 10
  air:
    default: 20
  maritime:
    default: 30
