shipment:
  boxes:
    min: 10
    max: 10
  stems_per_box:
    default: 200
    air:
      default: 200
    maritime:
      default: 200
  origins:
    - Netherlands
    - Mexico
    - Israel
    - Japan
    - New Zealand
    - India
    - Tanzania
  flowers:
    - Hyacinthus
    - Rosa
    - Gerbera
    - Agapanthus
    - Aegilops
    - Protea
    - Liatris
    - Mokara
    - Anemone
    - Actinidia
  ports:
    - NY JFK CBP
    - FL Miami Air CBP
    - HI Honolulu CBP
    - AZ Phoenix CBP
    - VA Dulles CBP
    - CA San Francisco CBP
    - WA Seattle Air CBP
    - TX Brownsville CBP
    - WA Blaine CBP
# f280_file: F280_sample.csv
# aqim_file: aqim_2011_2020_joined_stems_boxes.csv
#aqim_file: blank_aqim_for_testing.csv
pest:
  infestation_unit: box
  infestation_rate:
    distribution: beta
    value: 0.01
    parameters:
      # stems
      #- 0.9998207923
      #- 5578.1175514
      # boxes
      #- 0.942631386983
      #- 273.264725126
      # both
      #- 0.243875716307
      #- 223.427186223
      # centered at 0.7%
      - 9.99240788476
      - 1417.4944328
  arrangement: clustered
  clustered:
    max_infested_units_per_cluster: 200
    distribution: random
    random:
      max_cluster_stem_width: 600
  random_box:
    probability: 0.2
    ratio: 0.5
# release_programs:
#   naive_cfrp:
#     flowers:
#       - Hyacinthus
#       - Gerbera
#       - Rosa
#       - Actinidia
#     max_boxes: 10 # do not apply to shipments larger than
inspection:
  unit: boxes
  within_box_proportion: 1
  sample_strategy: proportion
  min_boxes: 0
  proportion:
    value: 0.02
  hypergeometric:
    detection_level: 0.1
    confidence_level: 0.95
  fixed_n: 10
  selection_strategy: random
  hierarchical:
    outer: random
    interval: 3
